### ISSUE TITLE
Worried about performance

### ISSUE THREAD

**Issue by ondrejmirtes** [staabm/phpstan-dba#144]
Hi, I really like this idea, it's definitely needed, but the fact this extension asks the actual database engine about each analysed query isn't optimal. Sometimes the database doesn't even live on the same machine where PHPStan is running.

I think it'd be much more interesting to download the database structure before the analysis (or let the user provide an actual static dump because sometimes it's even versioned in the repository) and then parse the queries and figure out the types by custom logic in the extension itself.

WDYT?

**Comment by staabm** [comment]
Hey Ondrej,

thx for the feedback.

as it stands right now we are asking the database, because this gives us the ability to have a result-set schema, not just a database schema. with this metadata we are able to also infer types for [aggregate functions](https://github.com/staabm/phpstan-dba/blob/2130c947ef72f5b5457fd7b0cfe85cd60f0d3f3f/tests/data/pdo.php#L141-L146) and we also get the [nullable-types on joins for free](https://github.com/staabm/phpstan-dba/blob/2130c947ef72f5b5457fd7b0cfe85cd60f0d3f3f/tests/data/pdo.php#L115-L120) without the need to parse the actual database query.

> Sometimes the database doesn't even live on the same machine where PHPStan is running.

for this case phpstan-dba supports [record & replay](https://github.com/staabm/phpstan-dba#record-and-replay). when replay-ing the queries we also see a 2-2.5x improved performance.

note, recording has a [open issue though](https://github.com/staabm/phpstan-dba/issues/93)


> I think it'd be much more interesting to download the database structure before the analysis

as mentioned above, this would not bring us on feature parity with what we have atm - I guess.
maybe we could use something like https://github.com/vimeo/php-mysql-engine to simulate a real database. but this in turn.

these are just my thoughts though, and I am open for experiements to improve phpstan-dba performance if we can.

**Comment by ondrejmirtes** [comment]
Yeah, "record and replay" seems reasonable, thanks :)
